%%
inF = '/clusterfs/nvme/matthewmueller/cudasirecon/test_data/raw.tif';
oF = '/clusterfs/nvme/matthewmueller/cudasirecon/test_data/out.tif';
otfF = '/clusterfs/nvme/matthewmueller/cudasirecon/test_data/otf.tif';
inFol = '/clusterfs/nvme/matthewmueller/cudasirecon/test_data';
inImg = parallelReadTiff([inFol '/raw.tif']);
otf = parallelReadTiff(otfF);
%%
inN = 'RAW_exp01_CamA_ch0_CAM1_stack0000_560nm_0000000msec_0084790941msecAbs_-01x_-01y_-01z_0002t';
inFF = '/clusterfs/nvme/Data/20220428_Aang_SIM_tiledDCagain/beadData/SIM_3Beam_single/RAW_exp01_CamA_ch0_CAM1_stack0000_560nm_0000000msec_0084790941msecAbs_-01x_-01y_-01z_0002t.tif';
%oFF = '/clusterfs/nvme/matthewmueller/SIMtestdata_fromFred/out.tif';
otfFF = '/clusterfs/nvme/Data/20220428_Aang_SIM_tiledDCagain/beadData/SIM_3Beam_single/OTF_c1_ls_0p3.tif';
inFolF = '/clusterfs/nvme/Data/20220428_Aang_SIM_tiledDCagain/beadData/SIM_3Beam_single';
inImgF = parallelReadTiff([inFolF '/' inN '.tif']);
otfF = parallelReadTiff(otfFF);
configF = [inFolF '/config-tiff_singleMatt.txt'];
%%
inN = 'RAW_exp01_CamA_ch0_CAM1_stack0000_560nm_0000000msec_0504969645msecAbs_-01x_-01y_-01z_0000t';
inFF = '/clusterfs/nvme/Data/Aang_SIM/20220601_SIM_beads/exp02_FOV1024x1024_250nmZ/RAW_exp01_CamA_ch0_CAM1_stack0000_560nm_0000000msec_0504969645msecAbs_-01x_-01y_-01z_0000t.tif';
otfFF = '/clusterfs/nvme/Data/Aang_SIM/20220601_SIM_beads/exp02_FOV1024x1024_250nmZ/mat/otf_100nm_560nm_C1.tif';
inFolF = '/clusterfs/nvme/Data/Aang_SIM/20220601_SIM_beads/exp02_FOV1024x1024_250nmZ/mat';
inImgF = parallelReadTiff(['/clusterfs/nvme/Data/Aang_SIM/20220601_SIM_beads/exp02_FOV1024x1024_250nmZ/' inN '.tif']);
otfF = parallelReadTiff(otfFF);
configF = [inFolF '/config-tiff_singleMatt.txt'];
%%
% Look below for env instructions

mexcuda('-v','-output', 'cudaSireconDriverMexTest.mexa64','-I/clusterfs/nvme/matthewmueller/cudasireconMex/src/', ...
    '-I/clusterfs/nvme/matthewmueller/cudasireconMex/src/Buffers', ...
    '-I/clusterfs/nvme/matthewmueller/cudasireconMex/src/cudaSirecon', ...
    '-I/clusterfs/nvme/matthewmueller/cudasireconMex/src/IVE/linux64/INCLUDE', ...
    '-I/global/home/groups/software/sl-7.x86_64/modules/cudasirecon/1.0.0/include',...
    '-L/global/home/groups/software/sl-7.x86_64/modules/cudasirecon/1.0.0/lib',...
    '-ltiff', ...
    '-lBuffer', ...
    '-lboost_atomic', ...
    '-lboost_filesystem', ...
    '-lboost_program_options', ...
    '-lboost_system', ...
    '-lcudasirecon', ...
    '-lcublasLt', ...
    '-lcublas', ...
    '-lcudart', ...
    '-lcufft', ...
    '-lcufftw', ...
    '-lcupti', ...
    '-lcurand', ...
    '-lcusolverMg', ...
    '-lcusolver', ...
    '-lcusparse', ...
    '-licudata', ...
    '-licui18n', ...
    '-licuio', ...
    '-licutest', ...
    '-licutu', ...
    '-licuuc', ...
    '-llapack', ...
    '-lX11', ...
    '-lgomp', ...
    'cudaSireconDriverMex.cpp', ...
    'cudaSirecon.cpp', ...
    'boostfs.cpp', ...
    'interface.cpp', ...
    'gpuFunctionsImpl.cu', ...
    '/clusterfs/nvme/matthewmueller/cudasireconMex/src/Buffers/Buffer.cpp', ...
    '/clusterfs/nvme/matthewmueller/cudasireconMex/src/Buffers/CPUBuffer.cpp', ...
    '/clusterfs/nvme/matthewmueller/cudasireconMex/src/Buffers/GPUBuffer.cpp')

%% Debug
% sim is the correct env
% Don't export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib?
% load module for cudasirecon?
% matlab 2022a
% gcc version 10 or less needed. Using 6.4.0 works, others do not?
%{
ISA1001
module unload matlab/r2023a
module unload gcc/12.2.0
module load gcc/6.4.0
module load matlab/r2022a
conda activate sim
matlab&
%}


% added boostfs.cpp and interface.cpp
    %['-I' getenv('CONDA_PREFIX') '/include'] , ...
    %['-L' getenv('CONDA_PREFIX') '/lib'], ...
mexcuda('-v','-g','-output', 'cudaSireconDriverMex.mexa64','-I/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/', ...
    '-I/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/Buffers', ...
    '-I/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/cudaSirecon', ...
    '-I/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/IVE/linux64/INCLUDE', ...
    '-I/global/home/groups/software/rocky-8.x86_64/modules/cudasirecon/1.0.0/include',...
    '-L/global/home/groups/software/rocky-8.x86_64/modules/cudasirecon/1.0.0/lib',...
    '-ltiff', ...
    '-lBuffer', ...
    '-lboost_atomic', ...
    '-lboost_filesystem', ...
    '-lboost_program_options', ...
    '-lboost_system', ...
    '-lcudasirecon', ...
    '-lcublasLt', ...
    '-lcublas', ...
    '-lcudart', ...
    '-lcufft', ...
    '-lcufftw', ...
    '-lcupti', ...
    '-lcurand', ...
    '-lcusolverMg', ...
    '-lcusolver', ...
    '-lcusparse', ...
    '-licudata', ...
    '-licui18n', ...
    '-licuio', ...
    '-licutest', ...
    '-licutu', ...
    '-licuuc', ...
    '-llapack', ...
    '-lX11', ...
    '-lgomp', ...
    'cudaSireconDriverMex.cpp', ...
    'cudaSirecon.cpp', ...
    'boostfs.cpp', ...
    'interface.cpp', ...
    'gpuFunctionsImpl.cu', ...
    '/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/Buffers/Buffer.cpp', ...
    '/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/Buffers/CPUBuffer.cpp', ...
    '/clusterfs/nvme/matthewmueller/Matlab-cudaSiRecon/src/Buffers/GPUBuffer.cpp')
